/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.Dbconnection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MT
 */
public class thembaohiem extends javax.swing.JFrame {

    /**
     * Creates new form thembaohiem
     */
    public thembaohiem() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jboxdanhsachbaohiem = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtngaybatdau = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtthoihanbaohiem = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtphibaohiem = new javax.swing.JTextField();
        btndangkibaohiem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnchon = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Đăng ký gói bảo hiểm");

        jboxdanhsachbaohiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Các loại gói bảo hiểm", "Gói bảo hiểm loại một", "Gói bảo hiểm loại hai", "Gói bảo hiểm loại ba" }));
        jboxdanhsachbaohiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jboxdanhsachbaohiemActionPerformed(evt);
            }
        });

        jLabel2.setText("Danh sách bảo hiểm:");

        jLabel7.setText("Ngày bắt đầu bảo hiểm:");

        txtngaybatdau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngaybatdauActionPerformed(evt);
            }
        });

        jLabel8.setText("Thời hạn bảo hiểm(tháng):");

        txtthoihanbaohiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtthoihanbaohiemActionPerformed(evt);
            }
        });

        jLabel9.setText("Mức phí bảo hiểm dự kiến:");

        txtphibaohiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphibaohiemActionPerformed(evt);
            }
        });

        btndangkibaohiem.setText("Đăng kí bảo hiểm");
        btndangkibaohiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangkibaohiemActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(table);

        btnchon.setText("chọn thông tin bảo hiểm");
        btnchon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btndangkibaohiem, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jboxdanhsachbaohiem, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtngaybatdau, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtthoihanbaohiem, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtphibaohiem, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnchon, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jboxdanhsachbaohiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtngaybatdau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(8, 8, 8)
                        .addComponent(txtthoihanbaohiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtphibaohiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(btndangkibaohiem))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnchon)))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndangkibaohiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangkibaohiemActionPerformed
        // TODO add your handling code here: đăng kí bảo hiểm

        String loaiBaohiem = (jboxdanhsachbaohiem.getSelectedItem().toString()); // Giả sử combobox chứa PolicyID
        String startDate = txtngaybatdau.getText();
        String endDate = txtthoihanbaohiem.getText();
        String status = "active"; // Mặc định là active

        // Kiểm tra nếu `customerId` chưa được thiết lập
        if (customerId == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng ký thông tin khách hàng trước khi đăng ký bảo hiểm.");
            return;
        }

        String sql = "INSERT INTO CustomerPolicies (CustomerID, PolicyID, StartDate, EndDate, Status) VALUES (?, ?, ?, ?, ?)";

        try (Connection conn = Dbconnection.getConnection(); PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setInt(1, customerId); // Truyền CustomerID
            pstmt.setString(2, loaiBaohiem);
            pstmt.setString(3, startDate);
            pstmt.setString(4, endDate);
            pstmt.setString(5, status);

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Đăng ký bảo hiểm thành công!");

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi đăng ký bảo hiểm.");
        }
    }

    private void loadPolicies() {
        String sql = "SELECT PolicyID, PolicyName FROM Policies";
        try (Connection conn = Dbconnection.getConnection(); PreparedStatement pstmt = conn.prepareStatement(sql); ResultSet rs = pstmt.executeQuery()) {
            while (rs.next()) {
                String policy = rs.getInt("PolicyID") + " - " + rs.getString("PolicyName");
                jboxdanhsachbaohiem.addItem(policy);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btndangkibaohiemActionPerformed
 public void saveCustomerPolicy() {
    // Kiểm tra xem có dòng nào trong bảng khách hàng được chọn hay không
    int selectedCustomerRow = table.getSelectedRow();
    if (selectedCustomerRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn khách hàng.");
        return;
    }

    // Lấy CustomerID từ dòng khách hàng được chọn
    int customerId = (int) table.getValueAt(selectedCustomerRow, 0);

    // Lấy gói bảo hiểm được chọn từ jboxdanhsachbaohiem
    String selectedPolicy = (String) jboxdanhsachbaohiem.getSelectedItem();
    if (selectedPolicy == null) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn gói bảo hiểm.");
        return;
    }

    // Tách PolicyID từ chuỗi "PolicyID - PolicyName"
    int policyId = Integer.parseInt(selectedPolicy.split(" - ")[0].trim());

    // Câu lệnh SQL để thêm vào bảng CustomerPolicies
    String sql = "INSERT INTO CustomerPolicies (CustomerID, PolicyID) VALUES (?, ?)";
    try (Connection conn = Dbconnection.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {

        pstmt.setInt(1, customerId);
        pstmt.setInt(2, policyId);
        pstmt.executeUpdate();
        
        JOptionPane.showMessageDialog(this, "Đã lưu thành công gói bảo hiểm cho khách hàng.");
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi lưu dữ liệu.");
    }
}

    public void loadData(){
        DefaultTableModel tableModel = new DefaultTableModel(new String[]{"Mã khách hàng", "Tên khách hàng", "Số điện thoại"}, 0 );
        String sql = "SELECT CustomerID, FullName, Phone  FROM Customers";
        try (Connection conn = Dbconnection.getConnection(); PreparedStatement pstmt = conn.prepareStatement(sql); ResultSet rs = pstmt.executeQuery()) {
            while (rs.next()) {
                //String policy = rs.getInt("PolicyID") + " - " + rs.getString("PolicyName");
                int makh = rs.getInt("CustomerID");
                String Name =   rs.getString("FullName");
                String phone = rs.getString("Phone");
                tableModel.addRow(new Object[]{makh, Name, phone});
            }
            table.setModel(tableModel);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
   

    private void txtphibaohiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphibaohiemActionPerformed
        // TODO add your handling code here: phí bảo hiểm
    }//GEN-LAST:event_txtphibaohiemActionPerformed

    private void txtthoihanbaohiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtthoihanbaohiemActionPerformed
        // TODO add your handling code here: thời hạn bảo hiểm
    }//GEN-LAST:event_txtthoihanbaohiemActionPerformed

    private void txtngaybatdauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtngaybatdauActionPerformed
        // TODO add your handling code here: Ngày bắt đầu
    }//GEN-LAST:event_txtngaybatdauActionPerformed
    private void loadCustomers() {
       
    }
    private void jboxdanhsachbaohiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jboxdanhsachbaohiemActionPerformed
        // TODO add your handling code here: Danh sách bảo hiểm
    }//GEN-LAST:event_jboxdanhsachbaohiemActionPerformed

    private void btnchonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchonActionPerformed
        // TODO add your handling code here:
         // Kiểm tra xem có dòng nào trong bảng khách hàng được chọn hay không
    int selectedCustomerRow = table.getSelectedRow();
    if (selectedCustomerRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn khách hàng.");
        return;
    }

    int customerId = (int) table.getValueAt(selectedCustomerRow, 0);
    String fullName = (String) table.getValueAt(selectedCustomerRow, 1);  // Lấy tên khách hàng từ cột FullName
    String phone = (String) table.getValueAt(selectedCustomerRow, 2);  
    // Câu lệnh SQL để lưu khách hàng vào bảng CustomerPolicies
    String sql = "INSERT INTO CustomerPolicies (CustomerID) VALUES (?)";
    try (Connection conn = Dbconnection.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {
        
        pstmt.setInt(1, customerId);
            
        pstmt.executeUpdate();
        
        // Hiển thị thông báo thành công
        JOptionPane.showMessageDialog(this, "Đã lưu thành công thông tin khách hàng.");

        // Làm mới lại dữ liệu trong bảng khách hàng nếu cần
        loadData();

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi lưu dữ liệu: " + e.getMessage());
    }
    
    }//GEN-LAST:event_btnchonActionPerformed
    private int customerId;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(thembaohiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(thembaohiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(thembaohiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(thembaohiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new thembaohiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchon;
    private javax.swing.JButton btndangkibaohiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JComboBox<String> jboxdanhsachbaohiem;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtngaybatdau;
    private javax.swing.JTextField txtphibaohiem;
    private javax.swing.JTextField txtthoihanbaohiem;
    // End of variables declaration//GEN-END:variables
}
